### ISSUE TITLE
Отзыв PHP7 наиболее полное руководство

### ISSUE THREAD

**Issue by alexrybin** [igorsimdyanov/php7#1]
Прошлая книга Катерова по содержанию напоминала следующий учебник английского языка " Подлежащее в английском языке ..... а вот в немецком .....  а в китайском .... . "  Он знает много языков программирования - молодец я рад за него. Я купил книгу по PHP и хочу чтобы мне рассказывали об этом языке и мне глубоко плевать что там в языке C, ПАСКАЛЬ и УБУНТУ.  При этом что такое константа с динамическим именем не понятно и не только мне (посмотрите в интернете) В самом начале книги даются примеры с классами, откуда я должен знать о классах, о которых будет рассказано через 300 страниц. В общем это справочник для специалистов, сдвинутых на языке C. Что либо понять не зная языка PHP не возможно. Прошлое наиболее полное руководство было намного лучше, судя по всему потому что там не было Катерова.

**Comment by igorsimdyanov** [comment]
Правильно понимаю, что новое издание не читали, не собираетесь, но осуждаете? Ну что ж, спасибо за критику, учтем в третьем издании :)
