### ISSUE TITLE
Нововведение в функции define()

### ISSUE THREAD

**Issue by peacefulseeker** [igorsimdyanov/php7#10]
Стр. 143
Функция define() теперь имеет другой вид, а именно 3 аргумент $case_insensitive. Ранее было $case_sensitive;
http://php.net/manual/ru/function.define.php
bool define ( string $name , mixed $value [, bool $case_insensitive = false ] ).
То есть сейчас если стоит true, то константа CONSTANT будет равна constant

**Comment by igorsimdyanov** [comment]
Спасибо за замечание! В новом издании "PHP 8", это будет исправлено.
