### ISSUE TITLE
PDF версия будет?

### ISSUE THREAD

**Issue by hepoju** [igorsimdyanov/php7#12]
Привет, Игорь! А есть в наличии pdf версия? Тоже поинтересовало это книжечка. Для кругозора же хоть как-то немного нужно прочесть, что там изменился в php.

**Comment by igorsimdyanov** [comment]
Добрый вечер!

Издательство выпустило [PDF-версии](url=http://www.ozon.ru/context/detail/id/141044025/?partner=softtimeru). К сожалению, пока нет возможности внести исправления, которые вы публикуете в issues в текущее издание, но при первой же возможности они будут учтены.

PS Кроме того в ближайшие месяцы издательством БХВ-Петербург будет выпущено издание "Самоучитель PHP 7" с упором на ООП (паттерны), PostgreSQL, NoSQL база данных Redis, в котором будут описаны разделы современного PHP, которые остались без внимания "PHP 7. В подлиннике". Корректура уже завершена, т.е. можно ждать издания в ближайшем будущем.

**Comment by Knayz** [comment]
Извините за вопрос, Игорь, есть ли новости по Самоучитель PHP 7. Более полугода прошло, а книга еще не выходила.

**Comment by igorsimdyanov** [comment]
Да, тоже с нетерпением жду. Издательство сообщает, что ее издание было перенесено на 2018 год (6 номер на издание, не могу сказать, как быстро).
