### ISSUE TITLE
Хэш-функции

### ISSUE THREAD

**Issue by GueroSF** [igorsimdyanov/php7#14]
Здравствуйте. Как быть, не знаю :) На странице 277 вы призываете "везде применять md5() вместо crypt()", в тоже время на php.net есть такое: 
"
Почему популярные хэширующие функции, такие как md5() и sha1() не подходят для паролей?
Такие хэширующие алгоритмы как MD5, SHA1 и SHA256 были спроектированы очень быстрыми и эффективными. При наличии современных технологий и оборудования, стало довольно просто выяснить результат этих алгоритмов методом "грубой силы" для определения оригинальных вводимых данных.

Из-за той скорости, с которой современные компьютеры могут "обратить" эти хэширующие алгоритмы, многие профессионалы компьютерной безопасности строго не рекомендуют использовать их для хэширования паролей.
"
http://php.net/manual/ru/faq.passwords.php#faq.passwords.fasthash
, ну и рекомендуют там применять специальные функции (password_hash() и т.п. ), описание которых ещё мне не встречались в вашей книге.
Стоит использовать password_hash() и т.п. или остаться на md5 и соль?

**Comment by igorsimdyanov** [comment]
Да, использовать `password_hash()` определенно стоит, хотя бы потому, что он "солит" ваш пароль автоматически, или он может задать сложность вычисления, здорово увеличивая стоимость подбора пароля по сравнению с традиционным md5. Однако, при его использовании есть особенности. Например, по умолчанию он возвращает для одной и той же строки разные hash-коды

```
<?php
$pass1 = password_hash('hello', PASSWORD_DEFAULT);
$pass2 = password_hash('hello', PASSWORD_DEFAULT);
echo $pass1 == $pass2 ? 'равны' : 'не равны'; // не равны
```

Если вы хотите получить одинаковые значения, вам потребуется задать "соль" вручную

```
<?php
$pass1 = password_hash('hello', PASSWORD_DEFAULT, ['salt' => 'секретная_соль']);
$pass2 = password_hash('hello', PASSWORD_DEFAULT, ['salt' => 'секретная_соль']);
echo $pass1 == $pass2 ? 'равны' : 'не равны'; // равны

```
Да, `password_hash()` более предпочтительный и удобный инструмент и своя соль.
