### ISSUE TITLE
Завершение книги.

### ISSUE THREAD

**Issue by GueroSF** [igorsimdyanov/php7#15]
Здравствуйте.

Не хватает после последней главы, какого-нибудь заключения. 
Может какой нибудь список литературы или пару напутствующих слов.

Спасибо за книгу!

**Comment by igorsimdyanov** [comment]
Добрый день, спасибо за добрый отзыв!

Да, вы абсолютно правы, тоже думал на эту тему, но, к сожалению, такое заключение будет только в книге "Самоучитель PHP 7", которая выходит в ближайшие месяцы. Список литературы я зарекся составлять, так как во-первых он довольно быстро устаревает, во-вторых сейчас переводится в разы меньше, чем переводилось еще лет 5 назад. Я бы лишь обозначил спектр технологий, на которые стоило бы обратить внимание PHP-разработчику. Приведу заключение из PHP 7 — оно актуально и для читателей "PHP 7. В подлиннике". Сразу оговорюсь, что здесь не упоминаются PostgreSQL и Redis, которые рассмотрены в книге "Самоучитель PHP 7". Подразумевается, что они следуют в начале списка.

> 
> Книга завершена, но ваше обучение Web-технологиям на этом не окончено. За пределами книжных страниц осталось множество неохваченных областей, которые вам придется штурмовать при помощи других изданий или самостоятельно. Вот далеко не полный список того, что не вошло в книгу или освещено недостаточно подробно:
> 
> - шаблоны проектирования;
> - стандарты кодирования PSR;
> - современные PHP-фреймворки (Symfony, Laravel и Yii);
> - система контроля версий Git;
> - протокол, серверы и клиенты SSH;
> - протокол HTTP;
> - детально знакомство с современными возможностями SQL;
> - очереди (на базе Redis и RabbitMQ);
> - Web-серверы (Apache, nginx);
> - системы полнотекстового поиска (ElasticSearch, Sphinx);
> - регулярные выражения;
> - знакомство с основами UNIX;
> - автоматическое развертывание серверов (Ansible, Puppet, Chef);
> - современные JavaScript-фреймворки (React.js, Backbone.js, Angular);
> - обработка изображений средствами GDLib и ImageMagic;
> - технологии виртуализации (Docker, Vagrant, VirtualBox);
> - тестирование PHP-кода (PHPUnit, phpspec).
> 
> Эта своеобразная дорожная карта, по маршрутам которой можно направить свои усилия. Технологии тут не выстроены в каком-то определенном порядке, но все они используются для создания современных Web-сайтов.
> 
> Кроме того, следует помнить, что основной залог успеха в программировании — это кодирование. Только разработка реальных проектов приносит глубокое понимание технологий, причин их возникновения, преимуществ и трудностей использования их в той или иной ситуации.
> 
> Удачи!
>
