### ISSUE TITLE
Не работает пример кода forms/cookies.php. Листинг 8.6

### ISSUE THREAD

**Issue by DranyValentin** [igorsimdyanov/php7#17]
Выдает ошибку: 
_Warning: Cannot modify header information - headers already sent by (output started at ..._
Предупреждение выдает на ф-ции setcookie()

**Comment by KrikunovAlexey** [comment]
Пример рабочий, при условии что это весь код в файле.
Вы наверняка выводите какую либо информацию(HTML-код, print, var_dump, echo и прочее) до setcookie
