### ISSUE TITLE
calendar.php ошибка

### ISSUE THREAD

**Issue by mitrosoft** [igorsimdyanov/php7#18]
в 43 строке вместо 
  $cal = makeCal($now['year'], $now['mon'] - 1);
необходимо
  $cal = makeCal($now['year'], $now['mon']);
Повезло, что проверял в январе (календарь оказался  пустой), в остальные месяцы выводится календарь за предыдущий месяц

**Comment by KuznetsovAlexamnder** [comment]
$n = - ($wday - 2);  заменить на  $n = - ($wday + 2);

**Comment by pe2** [comment]
> в 43 строке вместо
> $cal = makeCal($now['year'], $now['mon'] - 1);
> необходимо
> $cal = makeCal($now['year'], $now['mon']);
> Повезло, что проверял в январе (календарь оказался пустой), в остальные месяцы выводится календарь за предыдущий месяц

Соглашусь, а еще помимо этого при определении первого дня в месяце на самом деле определяется номер текущего дня.
Чтобы определить номер первого дня в месяце - `$wday = date("N", mktime(0, 0, 0, $month, 1, $year));`

**Comment by evgeny89** [comment]
Большое спасибо) ошибки в коде, сподвигли самому запариться в написании календаря) но т.к. что-то я не смог собрать в голове хороший алгоритм - решил писать решая проблемы на лету) получилось криво ужасно, почему-то все на условиях, но по крайней мере понимаю как оно там работает) а вот в листинге вобще не сообразил, из-за ошибок именно, т.к. потерял нить где какая переменная в данный момент времени, что именно в себе содержит) но спасибо за опечатки))

**Comment by mesolaries** [comment]
Исправил код календаря #31

**Comment by igorsimdyanov** [comment]
Спасибо! Внес исправление в новое издание PHP 8
