### ISSUE TITLE
Перечисления

### ISSUE THREAD

**Issue by Phjester** [igorsimdyanov/php7#19]
В книге не нашёл реализацию перечислений. 
Знаю что PHP нет перечислений, но реализовать можно с помощью классов. Считаю что это необходимо включить в книгу, потому что использование перечислений упрощает чтение и поддержку кода. Это отличный инструмент.

**Comment by igorsimdyanov** [comment]
В PHP 8.0 добавили перечисления, они будут описаны в новом издании "PHP 8.0"
