### ISSUE TITLE
Оформление книги

### ISSUE THREAD

**Issue by cavy24** [igorsimdyanov/php7#21]
Намного удобнее читать и ориентироваться в книге, если на каждой странице внизу или вверху подписана текущая глава.

**Comment by igorsimdyanov** [comment]
Согласен. К сожалению, согласно правилам оформления издательства глава указывается на каждой второй странице. Тут трудно что-либо поделать, даже если я внесу исправления, корректоры все-равно поправят согласно регламенту.
