### ISSUE TITLE
deprecated (unset) в php 7.2

### ISSUE THREAD

**Issue by sardykoivan** [igorsimdyanov/php7#25]
заметил такой момент:
Таблица 6.1. Преобразование типов в C-стиле
на странице 135 в (unset) $var; стало deprecated в php 7.2 (книга 2016 года) в книге не говорится о том что не рекомендуется использовать данную конструкцию.

**Comment by igorsimdyanov** [comment]
Более того, в PHP 8 такой тип приведения исключен. В новом издании "PHP 8.0" этот факт будет отражен (точнее исключен).
