### ISSUE TITLE
Серьезная путаница в наследовании и полиморфизме !!!

### ISSUE THREAD

**Issue by hwmaster2** [igorsimdyanov/php7#26]
Добрый день.
Глава 23.
На странице 476 дан класс StaticPage.
По логике подразумевается, что на основе входного параметра $id будет генерироваться уникальный ключ в методе id() (обратите внимание, там ошибка с именем переменной!).
Этот уникальный ключ используется для проверки наличия данных в кэше.
Однако в родительском классе Cached на основе этого метода создается уникальный ключ для хранилища используя вызов id('title'), что ведет к созданию ключа 'static_page_title'. Ни о каком входном параметре $id и речи не идет. Далее на стр.478 приводится пример использования всей этой конструкции, и опять с акцентом на уникальный ключ на основе входного параметра $id = 3. Да, метод $page->id($id), конечно вернет "static_page_3", но для memcached будет сгенерирован ключ "static_page_title"!!!
В итоге получается, что для объектов класса StaticPage с различными параметрами $id будет генерироваться одинаковый ключ!
Как же тогда полиморфизм, в чем он в данном случае? В том, что префикс разный в ключе? Хорошо, но тогда об этом и нужно говорить. И тогда следует упростить пример, и убрать всю эту кашу с memcached, т.к. оно работает неправильно.
А если, полиморфизм в том, что уникальный ключ генерируется в производном методе и на основе $id, то нужно исправить скрипты, чтобы в memcached сохранялись данные под ключем "static_page_title_$id" и "static_page_content_$id". разве не так?

**Comment by hwmaster2** [comment]
Думаю, что хорошим решением будет:
объявление приватного свойства private $id; в классе StaticPage, в конструкторе заносить туда входной параметр $id, а метод id() объявить без входных параметров и возвращать - return "static_page_{$this->id}";
В классе Cached()  вызывать метод id() без параметров.

**Comment by ghost** [comment]
Ошиблись? 

Алексей Дементьев
8 927 437 66 28

**Comment by hwmaster2** [comment]
Я не знаю, т.к. только учусь ООП.
Может чего я не понял. Но поразмыслив пришел к такому решению.
Думаю это подразумевалось.

**Comment by Demiat** [comment]
Мне вся эта каша вообще взорвала мозг! Конструкторы конструкторов... всё перетекает откуда-то куда-то.... синтаксис ООП объяснялся только вначале, потом такие штуки как return new class($this-title) даже не объясняется, что оказывается описание класса может принимать параметры подобно функциям.... + почему инструкция new появилась? Раньше для создания класса она была не нужна. 
В наследованиях принцип работы конструктора в конструкторе тоже пока до конца не ясен... какой-то геморой этот ООП

**Comment by igorsimdyanov** [comment]
Да, есть такая опечатка, внес исправление в новое издание PHP 8
