### ISSUE TITLE
Объясните пожалуйста откуда берется script.cgi

### ISSUE THREAD

**Issue by artdor-vitaliy** [igorsimdyanov/php7#27]
Здравствуйте. Сразу прошу прощения за глупый вопрос. Только начинаю познавать мир программирования на PHP. Купил Вашу книгу и начал изучать. На странице 60 вы упоминаете файл сценария script.cgi Но что в файле я так и не смог понять. Далее вы не однократно используете его, но где взять этот файл не описано. Скорее всего опытные программисты сразу поняли что к чему, но мне не понятно. Был бы очень благодарен, если разъясните. Спасибо большое

**Comment by ghost** [comment]
Мне ещё рано, только начинаю работать с книгой. Чтоб потом не переспрашивать, присоединяюсь к вопросу. Хотелось бы услышать ответ.

**Comment by vovs03** [comment]
@artdor-vitaliy Какой издательство и год издания?

**Comment by Valera8** [comment]
Здравствуйте! Также актуально и для меня! Остановился на этих страницах, но у меня на стр 61 и 62. Издательство БХВ-Петербург издание 2018

**Comment by Knayz** [comment]
Страница 73. Компиляция программы. Там этот файл создается. Правда не факт, что на серваке заработает. Пока не проверял.

**Comment by bubaololo** [comment]
не получается скомпилировать :
gcc 9.3.0 запинается на первой же строке и выдаёт

script.c:1:10: fatal error: time.h: Нет такого файла или каталога
    1 | #include <time.h>   // Директива нужна для инициализации функции rand()
      |          ^~~~~~~~
compilation terminated.

update
разобрался, пожалуй оставлю коммент, может другим новичкам пригодится, вобщем в моём случае нужно было прописать:

$ sudo apt-get update
$ sudo apt-get install build-essential manpages-dev

это устанавливает стандартные библиотеки си, в моём случае в linux mint они не шли

**Comment by SergeyErmolaev** [comment]
у меня просто скачивается файл script.cgi. Он не выполняется.

**Comment by SergeyErmolaev** [comment]
Запустил
sudo a2enmod cgi
sudo service apache2 restart
Не помогает
пишет The requested URL was not found on this server.

**Comment by bubaololo** [comment]
> 
> 
> у меня просто скачивается файл script.cgi. Он не выполняется.

у меня апач по умолчанию тоже не запускал скрипты, точно не помню но там у него в конфиге прописывается директория из которой он будет их запускать

**Comment by SergeyErmolaev** [comment]
> > у меня просто скачивается файл script.cgi. Он не выполняется.
> 
> у меня апач по умолчанию тоже не запускал скрипты, точно не помню но там у него в конфиге прописывается директория из которой он будет их запускать

У меня не получается настроить апач, скажите есть ли смысл заморачиваться? Вроде как автор пишет, что эта глава для примера, поясняющая почему не нужно работать с языком "с"?

**Comment by bubaololo** [comment]
> 
> 
> > > у меня просто скачивается файл script.cgi. Он не выполняется.
> > 
> > 
> > у меня апач по умолчанию тоже не запускал скрипты, точно не помню но там у него в конфиге прописывается директория из которой он будет их запускать
> 
> У меня не получается настроить апач, скажите есть ли смысл заморачиваться? Вроде как автор пишет, что эта глава для примера, поясняющая почему не нужно работать с языком "с"?

Совершенно спокойно пропускайте, если жалко времени, этот момент никак не связан с последующим материалом.
