### ISSUE TITLE
Ошибка в листинге 3.8

### ISSUE THREAD

**Issue by AsyncSoul78** [igorsimdyanov/php7#29]
Листинг 3.8 работает не правильно. Сразу при открытии cgi скрипта я вижу:

**"Привет, EST_URI=/cgi-bin/cookies.cgi!"** 

и тут же в браузер пишется кука с таким же значением. Хотя в скрипте она писаться должна только если if(query != NULL). Видимо не Null, раз пишется.

Проверял в двух браузерах на выделенном сервере. Думал может сам ошибся: забрал ваш листинг с гитхаба - то же самое. С помощью переменных проверил условие if(query != NULL) - оно срабатывает просто при открытии скрипта без параметров, как будто какие-то параметры в QUERY_STRING есть.

Если форму заполнить и отправить, то все работает нормально. 

Это ваша ошибка или у меня что-то не так?

**Comment by deniro21** [comment]
Руководствуясь ответом на Stackoverflow https://stackoverflow.com/a/10340671, я изменил проверку пустоты QUERY_STRING на следующую:
`if (query != NULL && query[0] != '\0')`
и все заработало.  Это легко проверить, скажем, таким скриптом:
```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main() {
  char *query = getenv("QUERY_STRING");

if (query != NULL && query[0] != '\0') {

   printf("Content-type: text/html\n\n");
   printf("<p>QUERY_STRING: %s",query);

  }else{

  printf("Content-type: text/html\n\n");
  printf("<p>QUERY_STRING: ПУСТО</p>");

}

}
```
Т.е. получается, что Сишная переменная может быть без параметров, но с каким-то ноликом и кука в вашем скрипте будет писаться в браузер с каким-то мусором из буфера, как будто параметры имеются.

Вы  проверяете листинги перед публикацией книги?

**Comment by AsyncSoul78** [comment]
Заменил проверку пустоты query с текущего:
`if(query != NULL) { // строка не пустая?`
на
`if(query != NULL && query[0] != '\0') { // строка не пустая?`
Теперь проверяет корректно и при первом запуске скрипта без параметров кука не пишется. Но в поле все равно вставляется кусок идентификатора сессии (без первых 5 символов), которую сервер всегда кладет в браузер.

Другая проблема объясняется так. Кусок REQUEST_URI, который, как я описал в топике, выводится в html при некорректной проверке переменной query, почему то получается от выражения query+5. Это иллюстрирует следующий скрипт:
```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
// начало программы
int main() {
  char *query = getenv("QUERY_STRING");
  printf("Content-type: text/html\n\n");
  printf("Query: %s", query+5);
}
```
На экране будет: Query: EST_URI=/cgi-bin/cookies.cgi' (если скрипт так называется)
Проверил в Chrome и Firefox. Хотя, если +5 убрать, то будет пустота (потому что переменная-то и должна быть пустой). Если запустить с параметрами, то все будет корректно.

**Comment by Knayz** [comment]
Да, вы правы здесь ошибка в коде. Потому что пустую строку нельзя сравнивать с NULL. Нулевой символ и нулевой указатель разные вещи. Поэтому проверка на пустую строку может выглядеть вот так 
`a[0] == '\0'`
или т.к. имя массива является указателем на первый элемент, а символ '\0' имеет код 0 то имеем
`*a == 0`
или
`!*a`

**Comment by Knayz** [comment]
Почему-то, и Apache и nginx создает всегда QUERY_STRING, даже если в урле её нет, в этом случае она равна пустой строке. Встроенный же сервер php не создает её в случае если в урле её нет.
