### ISSUE TITLE
Цифровая версия книги

### ISSUE THREAD

**Issue by alexdeia** [igorsimdyanov/php7#3]
Здравствуйте. 
Не могу найти книгу в электронном виде. Такой вариант есть в продаже?

**Comment by igorsimdyanov** [comment]
Здравствуйте, к сожалению, книга пока доступна только в бумажном виде. Возможно позже издательство примет решение выпустить ее в электронном виде. Если будут новости, обязательно сообщим.

**Comment by cgurubest** [comment]
Ребята, если вы держите связь с  издательством, а скорее всего так и есть, то очень прошу вас сообщить им, что есть больше кол-во людей, которые бы хотели покупать качественно издание в электронном виде. В данный момент получить бесплатный вариант не составляет проблем. Весь Топ забит ссылками на пиратский контент, а легального способа купить электронную версию нет.

**Comment by igorsimdyanov** [comment]
Спасибо, обязательно передадим в издательство.

**Comment by dmglazunov** [comment]
С удовольствием бы купил электронную версию и поддержал авторов, бумажную версию неудобно читать!

**Comment by igorsimdyanov** [comment]
Издательство выпустило [PDF-версию издания](http://www.ozon.ru/context/detail/id/141044025/?partner=softtimeru).

**Comment by cgurubest** [comment]
Не предусмотрена возможность, для тех кто купил бумажный вариант, получить PDF версию?

**Comment by igorsimdyanov** [comment]
Я думаю нет, так как довольно трудно однозначно зафиксировать факт покупки бумажной версии ) Если честно, бы если бы аналитики пришли бы ко мне с такой таской, я бы почесал бы голову как ее реализовать и мягко бы намекнул, что они хотят странного )

PS Вы я думаю так же как и я понимаете, что означает выпуск PDF ), через месяц вам достаточно будет протянуть руку, чтобы взять его бесплатно. Хотите нас с Димой поблагодарить - купите, если хотите мое разрешение берите PDF так ). Мы не получаем каких-то бешенных доходов, например доля книг в моем месячном доходе с книг не составляет и 2% и ваша доброе слово, поддержка, звездочка в github, толковое замечание к тексту, вообще любое упоминание книги где бы то ни было значит для меня много больше чем 27 рублей с купленного вами экземпляра ). Другое дело, что остальные от этих 27 рублей деньги заплаченные вами за издание, идут редакторам, корректорам, переводчикам, идут в том числе на выпуск новых книг как русскоязычных авторов, так и перевод англоязычной литературы. Сегодня вы разработчик, а завтра вам собирать команду и, возможно, от того, сколько вы вложили в книжный бизнес сегодня, зависит сколько какого качества разработчиков вы сможете нанять к себе в команду завтра. Меня вы точно не обидите скачиванием PDF (я даже обрадуюсь, если увижу, что книга пользуется на торренте спросом), но у же сегодня на русский не переводится до 2/3 того, что необходимо переводить. С удовольствием читаю на русском, но каждую вторую книгу я вынужден читать на английском. Я не боюсь, что профессионалы все более и более ориентируются на английский, я боюсь, что из-за этого все более и более новичков предпочитают путь, который ведет их не в IT и программирование, а среди них и те, кого этот путь мог бы сделать по-настоящему счастливыми.
