### ISSUE TITLE
Непонимание листинга 3.3

### ISSUE THREAD

**Issue by danil0919** [igorsimdyanov/php7#32]
В данный момент читаю 3-ю главу "CGI изнутри". Листинг 3.5 вызывает некоторые вопросы.
Функция url_decode декодирует входящую строку и результат записывает в ту же область памяти. Но декодированная строка будет короче (об этом говорится далее в главе). Т.е. , насколько я понимаю, условно, "первая половина" массива будет занята полностью  декодированной строкой, а "вторая половина" так и останется в конце массива в изначальном виде. 
Возможно, я не до конца понятно объяснил. Поэтому приведу пример: допустим в QUERY_STRING сейчас хранится закодированная пара животное=гусь, "%D0%B6%D0%B8%D0%B2%D0%BE%D1%82%D0%BD%D0%BE%D0%B5=%D0%B3%D1%83%D1%81%D1%8C", что после декодирования с помощью нашей функции превратится в животное=гусьD0%B2%D0%BE%D1%82%D0%BD%D0%BE%D0%B5=%D0%B3%D1%83%D1%81%D1%8C и эту же строку в листинге 3.6 мы вернем юзеру с ненужным "мусором".
Возможно, я что-то упустил, был бы рад услышать, где в своих рассуждениях я допустил ошибку.

**Comment by Knayz** [comment]
Потому что программа ноль-символ тоже копирует в позицию куда ссылается выражение *p++. Тем самым укорачивая строку. Фактически память выделена под старый массив. Но функция printf или другие функции ввода/вывода(в данной программе используется printf) прочитают строку только до ноль-символа.
