### ISSUE TITLE
Переменная $v после цикла foreach($a as $k=>&$v)

### ISSUE THREAD

**Issue by mafia8** [igorsimdyanov/php7#35]
Страница 205
ВНИМАНИЕ! 
Ссылочная переменная $v — это полноценная жесткая ссылка, которая не уничтожается после завершения работы цикла foreach! Таким образом, если вы попытаетесь что-то присвоить переменной $v в конце программы, изменения затронут последний элемент массива $numbers — ведь именно он соответствовал $v на последней итерации цикла! Как раз по этой причине мы используем переменную $elt, а не все ту же $v, в последнем цикле вывода листинга: иначе бы последний элемент массива $numbers, которому соответствует жесткая ссылка $v, "затирался" при последующей итерации по массиву. 

Это не так.

$a['a']=10;
$a['b']=20;
foreach($a as $k=>&$v) $v=5;
$v=100;
foreach($a as $k=>$v) echo $k.' '.$v.'<br>';
// a 5 b 5

**Comment by Knayz** [comment]
Попробуй в последней строчке 
`foreach($a as $key=>$val) echo $key.' '.$val.' ';`
