### ISSUE TITLE
Не работают CGI программы

### ISSUE THREAD

**Issue by galishmann** [igorsimdyanov/php7#4]
Когда пытаюсь запустить программу .CGI она не выполняется, а просто скачивается. Пробывал запускать через протокол file:// и через Nginx

**Comment by igorsimdyanov** [comment]
Так не получится, когда вы обращаетесь через протокол file:// вы идете в обход сервера, обращаясь к операционной системе, которая не готово выполнять CGI-файлы.

**Comment by galishmann** [comment]
А что нужно сделать чтобы заработало все как надо?

**Comment by igorsimdyanov** [comment]
Вообще CGI сейчас никто не пользуется, в случае nginx, вам потребуются отдельные модули для его поддержки, из коробки в нем уже только FastCGI, через который, кстати, работает и PHP. Если хочется попробовать запустить именно CGI-программу, проще всего воспользоваться Apache.
