### ISSUE TITLE
Как запустить CGI-сценарий из главы 3 в Linux?

### ISSUE THREAD

**Issue by ghost** [igorsimdyanov/php7#41]
Здавствуйте, уважаемые авторы!
Ваша книга очень хороша. Не могли бы вы подсказать, как запустить CGI-скрипт после компиляции GCC в Linux на примере Ubuntu?
Спасибо.

**Comment by systemdfan** [comment]
Тут всё достаточно просто. Сначала, надо установить на компьютер любой веб-сервер. На linux лучше всего для локального веб-сервера подходит [xampp](https://www.apachefriends.org/ru/index.html). Скачиваешь с сайта файл в формате .run, даёшь ему право на исполнение либо в файловом менеджере, либо с помощью комманды `sudo chmod +x имя_установщика.run`. Там графический установщик как в винде, думаю что спраишься. Установится сервер в директорию `/opt/lampp/`. Далее как написанно в книге, копируешь свой файл по стандартному для cgi-сценариев пути `/opt/lampp/cgi-bin/`. Потом необходимо запустить веб-сервер. Либо коммандой `sudo /opt/lampp/xampp start`, либо там ещё есть файл manager-linux-x64.run. Там графическая панель. Если сервер не запускается, посмотри не занят ли 80-й порт. Далее переходишь в браузере по адресу `http://localhost/cgi-bin/script.cgi` Вуаля - страница работает! Стопнуть сервер можно соответственно коммандой `sudo /opt/lampp/xampp stop`, либо опять же через графическую панель.
![image](https://user-images.githubusercontent.com/81460388/113509024-034f7180-955c-11eb-8afe-5fdaebc14725.png)

**Comment by SergeyErmolaev** [comment]
Прекрасно! xampp на ubuntu ставить не нужно, всё уже есть в коробке в папке /var/www проблема создать файл script.cgi, поскольку предложенная команда gcc script.c –o "script.cgi" не работает.

**Comment by SergeyErmolaev** [comment]
команда работает, но файл не исполняется, а скачивается

**Comment by SergeyErmolaev** [comment]
Запустил
sudo a2enmod cgi
sudo service apache2 restart
Не помогает

**Comment by systemdfan** [comment]
> Прекрасно! xampp на ubuntu ставить не нужно, всё уже есть в коробке

Но всё-равно в будущем удобнее будет разрабатывать используя xampp. Так почему бы его сразу не установить и не париться с этим всем?
