### ISSUE TITLE
Неверная информация в книге. Функция glob описание GLOB_BRACE

### ISSUE THREAD

**Issue by Knayz** [igorsimdyanov/php7#44]
Страница 340
описание параметра GLOB_BRACE в функции glob, написано в конце
К сожалению, задавать выражения с вложенными фигурными скобками нельзя;
На самом деле можно: в доке даже есть пример
https://www.php.net/manual/ru/function.glob.php

It is also possible to nest alternations like this:

`<?php`
`foreach (glob("{$dir}/*.{[jJ][pP]{,[eE]}[gG],[tT][iI][fF]{,[fF]}}", GLOB_BRACE) as $file) {`
   ` // finds both .jp(e)g and .tif(f) files`
    `// please note that you should double-check the file type, though`
`}`

**Comment by igorsimdyanov** [comment]
Спасибо! Поправлено в новом издании "PHP 8" (в процессе подготовки)
