### ISSUE TITLE
email.php

### ISSUE THREAD

**Issue by SergeyErmolaev** [igorsimdyanov/php7#46]
<?php ## "Активизация" адесов E-mail.
  $text = "Адреса: user-first@mail.ru, second.user@mail.ru.";
  $html = preg_replace(
    '{
      [\w-.]+             # имя ящика
      @
      [\w-]+(\.[\w-]+)*   # имя хоста
    }xs',
    '<a href="mailto:$0">$0</a>',
    $text
  );
  echo $html;
?>
Это совсем не работает!

**Comment by SergeyErmolaev** [comment]
"<?php ## "Активизация" адесов E-mail.
  $text = "Адреса: user-first@mail.ru, second.user@mail.ru.";
  $html = preg_replace(
    '{
      [\w-.]+             # имя ящика
      @
      [\w-]+(\.[\w-]+)*   # имя хоста
    }xs',
    '<a href="mailto:$0">$0</a>',
    $text
  );
  echo $html;
?>"

**Comment by SergeyErmolaev** [comment]
<? php ## "Активизация" адесов E-mail.
  $text = "Адреса: user-first@mail.ru, second.user@mail.ru.";
  $html = preg_replace(
    '{
      [\w-.]+             # имя ящика
      @
      [\w-]+(\.[\w-]+)*   # имя хоста
    }xs',
    '<a href="mailto:$0">$0</a>',
    $text
  );
  echo $html;
?>

**Comment by SergeyErmolaev** [comment]
## "Активизация" адесов E-mail.
  $text = "Адреса: user-first@mail.ru, second.user@mail.ru.";
  $html = preg_replace(
    '{
      [\w-.]+             # имя ящика
      @
      [\w-]+(\.[\w-]+)*   # имя хоста
    }xs',
    '<a href="mailto:$0">$0</a>',
    $text
  );
  echo $html;

**Comment by igorsimdyanov** [comment]
Не очень понятно, про какой листинг идет речь. Если не сложно укажите номер страницы?
