### ISSUE TITLE
Опечатки

### ISSUE THREAD

**Issue by akhromets** [igorsimdyanov/php7#5]
Опечатки/неточности из книги буду помещать сюда.

**Comment by ahromets** [comment]
1. Стр. 35. Опечатка. 3-ий снизу абзац. Цитирую: "высказал множество ценных замечаний по улучшению последний главы книги...".
2. Стр. 37. Ошибка. Цитирую: "мне всегда хотелось 'не много' поправить её". В данном случае "немного" пишется слитно.
3. Стр. 48. Первый адрес IPv6 почему-то расбросан на две строки, а остальные вместились в одну, хотя места хоть отбавляй. Не знаю, с чем это может быть связано.

**Comment by ahromets** [comment]
4. Стр. 144 листинг 6.4. В слове "echo" пропущен символ "e".

**Comment by ahromets** [comment]
5. Стр. 749. Опечатка в слове "Memcache" (написано "Memache").

**Comment by igorsimdyanov** [comment]
Большое спасибо!

**Comment by ahromets** [comment]
Стр. 233. Цитирую: "Таким образом, вероятнее всего, при работе с PHP версии вам никогда не придется...". Забыли написать версию.

**Comment by galishmann** [comment]
Стр 206 в конструкции list() вместо $born, $burn :)

**Comment by aleksejdyachkov** [comment]
Глава 12. Генераторы. Ошибка в названии листинга 12.12. Использование ключей. Файл ошибочно указан как keys.php Правильный видимо ref.php, потому что Листинг 12.11 тоже ссылается на keys.php

**Comment by aleksejdyachkov** [comment]
<-- Листинг 12.13. Каждый генератор - это объект. Файл object.php -->
<?php ## Каждый генератор - это объект
  function simple($from = 0, $to = 100)
  {
    for($i = $from; $i < $to; $i++) {
      echo "значение = $i<br />";
      yield $i;
    }
  }
  $generator = simple();
  echo gettype($hello); // object              ---------------------Выдаёт NULL, переменная $hello не иниц.
  echo gettype($generator); // object             ---------------------Наверно нужно так, чтобы был object ?
?>

**Comment by dimkaganin** [comment]
116 страница: "... он обладает внушительным набором инструментом."

**Comment by ahromets** [comment]
Стр. 269 третий абзац слово "превратиться" без мягкого знака пишется.

**Comment by Knayz** [comment]
Стр. 752 "Помещение данных в memcached" 1 абзац в конце: "по порту 112111".

**Comment by ahromets** [comment]
Стр. 369 Таблица 19.1 входная строка "10 September 2000" должна быть "10 September 2015".

**Comment by ahromets** [comment]
Стр. 377 Глава 20 Основы регулярных выражений "Листинги данной главы можно найти в подкаталоге date". Правильно "...в подкаталоге preg".

**Comment by ahromets** [comment]
Стр. 470 "чтобы сделать примеры главы немного абстрактным и более приближенным к реальности". Тут "абстрактными" и "приближенными" должно быть.

**Comment by ahromets** [comment]
Стр. 471 "В листинге 23.11 показано определение базового класс Page". Правильно "класса".

**Comment by ahromets** [comment]
Стр. 474 "Для гарантии, что все кэшируемые страницы будут извлекать данные из кэша, мы объявляем методы title() и content() финальными (final)". Здесь описан листинг 23.12, но в нем нет финальных методов.

**Comment by ahromets** [comment]
Стр. 494 "В результате скрипт завершиться ошибкой". Завершится в данном случае пишется без мягкого знака.

**Comment by ahromets** [comment]
Стр. 768 "Mazilla" пишется через "о".

**Comment by ahromets** [comment]
Стр. 792 Методы "между названием класса и круглой скобкой не должно быть пробела". Между названием метода и круглой скобкой.

**Comment by wooly-booly** [comment]
Стр. 241, в начале страницы, для того, чтоб код работал как предполагается,
 тернарный оператор должен выглядеть так:
return $e % 2 == 0 ? $e : false;

**Comment by asistent0** [comment]
Стр 130, пример работы с большими числами, у вас написано:
`<?php`
`    echo 1.8e307; // 1.8e+307`
`    echo 1.8e308; // INF`
`    echo $var - 1.8e307; // INF`
`?>`
и написано, "Любые операции с числом INF опять возвращают INF".
во первых `1.8e307` не является INF, судя по вашей записи;
во вторых вы в примере используете переменную которая не определена, если кто то захочет повторить ваш пример, столкнется с проблемой.
тут надо было бы или так сделать:
`echo 1 - 1.8e308 // INF`
или так можно было бы:
`$var = 1.8e308`
`    echo $var - 1.8e307; // INF`

А вообще книга классная, спасибо!

**Comment by asistent0** [comment]
Стр 145. Листинг 6.5 - не дописали результат работы скрипта.
Вы написали только как выглядит один вывод функции `var_export`, а второй, который показывает как обрабатывается вывод класса с приватной переменной упустили.
Без запуска листинга не понятно о чем идет речь дальше в книге.

**Comment by asistent0** [comment]
Стр 156, листинг 7.1, во время вывода вы пишите "Желтый прямоугольник в десятичном/двоичном примере", а дальше используете константу `GREEN`, и результат в комментариях для этого значения пишите.

**Comment by asistent0** [comment]
Стр 169, первый абзац после листинга 8.1.
непонятно зачем вы в скобках написали "перед этим сохранив его в файле test.php в корневом каталоге сервера", если дальше показываете пример строки запроса в котором имя файла qs.php.

**Comment by asistent0** [comment]
Стр 223, раздел про Факториал.
Вы написали если `n = 0`, то `n != 1`, а иначе `n != n * ((n - 1)!)`
Вы поставили пробел между n и !, а между ! и = его нет, что может читаться как n не равно 1 и т.д.

**Comment by SoraTM** [comment]
стр. 522
> К сожалению, в современной версии РНР реализация исключениями интерфейсов (а следовательно, и множественная классификация) не поддерживается. Точнее, вы можете создать класс-исключение, наследующий некоторый интерфейс, но попытка перехватить сгенерированное исключение по имени его интерфейса (а не по имени класса) не даст результата. Есть основания надеяться, что в будущих версиях РНР данное неудобство будет устранено. 

И далее на соседней странице (523) "Использование интерфейсов". Как так то?

**Comment by zer1** [comment]
Стр. 243 листинг 12.10. Ошибка в названий файла. Должно быть makerange_good.php а не makerange_bad.php.

**Comment by Div-Man** [comment]
Стр. 382, не работает файл ex03.php, емайлы не становятся ссылками

**Comment by duxa174** [comment]
Стр. 650. "Для того чтобы удалить из электронного адреса все нежелательные символы, можно воспользоваться константой FILTER_VALIDATE_EMAIL (листинг 36.2)". Должно быть "... FILTER_SANITIZE_EMAIL"

**Comment by ugsite** [comment]
Глава 36. Стр. 658.
> Фильтруемая строка может содержать **управляющие символы**, т.е. символы, **чей код 32**, например, табуляцию \t или перевод строки \n

Скорее всего в книге опечатка и имелось ввиду: **[чей код меньше 32](https://en.wikipedia.org/wiki/ASCII#ASCII_control_characters)**. 

Однако, к управляющим символам в ASCII также относится символ DEL ([код 127](https://en.wikipedia.org/wiki/ASCII#ASCII_control_characters)).

А в случае Unicode [к управляющим символам относятся](https://en.wikipedia.org/wiki/Control_character#In_Unicode) : U+0000-U+001F (C0 controls), U+007F (delete), и U+0080-U+009F (C1 controls).

То есть **управляющие символы - это не только символы с кодом < 32**.

Также в книге указано: (глава 36. стр. 658.)
> FILTER_FLAG_STRIP_LOW - удаляет **управляющие символы** (код меньше 32).

В [документации](http://php.net/manual/ru/filter.filters.flags.php): 
> FILTER_FLAG_STRIP_LOW - Удаляет символы, код которых <32.

**Comment by temaror** [comment]
Стр. 245 Написано "Использование ключей. Файл keys.php" должно быть "ref.php".
И на этой же странице где object.php ...echo gettype($hello); должно быть ...echo gettype($generator);

**Comment by tzhel** [comment]
Стр. 256 "Однако, в отличие от JavaScript, код заключается в фигурные `скбоки `.."

**Comment by tzhel** [comment]
269стр.
ENT_QUOTES - преобразует апострофы ' в &quot;, а кавыки " в &#039;

`кавычки`

**Comment by alderchiv** [comment]
Стр 128.
"Такого понятия, как указатель (как в С), в языке не существует - при присваивании переменная в большинстве случаев копируется один в один, какую бы сложную структуру она ни имела. Единственное исключение из этого правила — копирование переменной, ссылающейся на объект или массив: в этом случае объект остается в единственном экземпляре, копируется лишь ссылка на него..." 

Действительно же происходит копирование массива при присваивании.

"...при присваивании массива всегда происходит копирование значения. Чтобы скопировать массив по ссылке, вам нужно использовать оператор ссылки..."(http://php.net/manual/ru/language.types.array.php)

**Comment by igorsimdyanov** [comment]
Огромное спасибо за замечания, мы не можем реагировать на каждое из них. Но поверьте ваша работа не пропадает зря и при выпуске нового издания все они будут учтены.

**Comment by Rustamfm** [comment]
страница 47 внизу написано в скобках (шестнадцать 8-разрядных чисел) по моему должно быть (восемь 16-разрядных чисел)

**Comment by peacefulseeker** [comment]
Спасибо за замечательную книгу.
Отличные учительские навыки!

Немного правок и от меня:
- Стр. 372. Внутри кода либо устаревшый парметр "N", либо его описание неправильно к книге. На данный момент в документации пишется следующее:
N -> Порядковый номер дня недели в соответствии со стандартом ISO-8601 (добавлен в версии PHP 5.1.0)
- Стр. 398. preg_replace() с модификатором /e признан устаревшим вообще.
- Стр. 401. Ссылка битая - http://ru.php.net/manual/ru/pcre.pattern.syntax.php.
- Стр. 411. Вместо hrefCallback() - скорее всего подразумевалось hrefActivate(), которая прописана в листинге
- Стр. 439. "Как видите сообщение 'Все умерли' ... ". Имелось ввиду не самым первым а вторым по списку.
- Стр. 456. Забыл добавить строчку обнуления пароля в метод __sleep()
$this->password = "";
- return [ 'name', 'referrer', 'time' ];
- Стр. 472. в Функции public function render(), опечатка. 2 закрюывающихся тега <p>. Должно быть, выделил:
pulic function render() {
-    echo "<h1>" . htmlspecialchars( $this->title() ) . "</h1>";
-    echo "<p>" . nl2br( htmlspecialchars( $this->content() ) ) . "</p>";
- }
- Стр. 472. в Функции public function render(), опечатка. 2 закрюывающихся тега <p>. Должно быть
- Стр. 497. Листинг 25.5 Относительные ссылки на элементы. Файл few_relative.php а не few_use.php
- Стр. 507. Чаще встречается E_ALL~E_NOTICE(Подразумевалось E_ALL & ~E_STRICT) Иначе ошибка парсинга. PHP 7.1.0
- Стр. 634. Не работает код сессий handlers.php
- Стр. 650. .Для того, чтобы удалить из электронного адреса ...  можно воспользоваться константно FILTER_VALIDATE_ EMAIL(подразумевалось FILTER_SANITIZE_ EMAIL)
- Стр. 693. Синтаксис оператора RANAME (подразумевалось REPLACE)
- Стр. 719. Листинг button.php строка 3. Вместо ?? вроде как должно быть ?:
- Стр. 745.  Отправка данных методов POST. ..., состоящую из одного текстового поля (подразумевается из двух)
- Стр. 751. Внутри кода инстанциирования новок обьекта Memcacched() в комменте наверное имелось ввиду в 10 раз а не в 2 раза вероятность быть выбранным.
- Стр. 879. Не появляется никакое сообщение в Google Chrome, в случае, если нажимать НЕТ при обовлении страницы. файл bad.php
- Стр. 881. Неудивительно, но браузер выдаёт ошибку:
Cannot modify header information - headers already sent by
Нужно поместить скрипт на самый верх, тогда не будет выдаваться ошибка и перезагрузка будет работать нормельно без предупреждений
- стр 912(Строка 1). Заметьте, что расширение файла шаблона - HTM(а вот и нет, расширение у файла .php)
- Стр 913. все компоненты подключаются обычной иснтрукцией PHP include. Подразумевалось require_once как в листинге.
- Стр. 917. Ссылка на smarty битая. http://smarty.php.net => https://www.smarty.net/
- Приложение HTTP коды. <?php header("HTTP/1.1 301 Moved Remanently"); Подразумевалось Permanently.

**Comment by bergentroll** [comment]
Стр. 29 менеджерами пактов.

**Comment by ArtemMozolev** [comment]
Вложу свои 5 копеек. Только прошу учесть, что я новичок в PHP (как раз изучаю его по этой книге), так что поправьте меня, если что:
стр. 135: в верхнем абзаце в утверждении о возвращении функцией settype() значения false при попытке перевода нечислового значения в тип "integer" содержится ошибка. В данном случае нечисловая строка  (например "somestring") преобразуется как раз в целое число 0. Поэтому данное преобразование считается выполненным и функция возвращает true. Это проверяется простым условием: if (settype($b, "integer")) echo "Преобразование выполнено"; .
Во втором абзаце также ошибка: нижеперечисленные функции floatval(), strval(), intval() не преобразовывают переменную, указанную в ее параметрах (в скобках). Они возвращают, например, для intval($a), целое значение переменной в скобках: т.е., если $a = 24.3 (тип double), то функция intval($a) возвратит значение 24; а сама переменная $a при этом преобразована не будет - ее значение и тип так и останутся равными 24.3 и double соответственно. Это можно проверить дальнейшим применением функции gettype($a).
А вообще предлагаю вынести ЛОГИЧЕСКИЕ ошибки книги в отдельную от ОПЕЧАТОК тему.

**Comment by vsk-Result** [comment]
Стр. 791 "class News exntends Page implements Seo" соответственно опечатка в слове exntends (extends)

**Comment by lezhnev74** [comment]
В главе "Функции форматных преобразований" (стр.271) среди спицификаторов формата нет "[спецификатора знака](http://php.net/manual/en/function.sprintf.php)".

**Comment by timurmelnikov** [comment]
Страница 137.
строка - $r = & $A['ресторан']; // $r - то же, что и элемент с индексом 'ресторан'
Оператор ссылок, указан не однозначно. В коде - так "= &", а в тексте, так - "=&" (без пробела)

**Comment by alexverkhola** [comment]
Стр 259.
Особенности strpos()
В строке "PHP предоставляет в распоряжение разработчиков фуннкцию strpos($what, $str)"
нужно поменять местами параметры на strpos($str,  $what)

**Comment by Warlock-9000** [comment]
Пришлось прочесть все комментарии, но вроде "своих" ошибок я  не нашел, так что вот:

стр 547 -> листинг 27.8 ( Использование метода `bindTo()` ). Файл view.php
`public function body(){
    return nl2br(htmlspecialchars($this->title));
}`
Возможно вы имели в виду не title, а body?

стр 564 -> таблица 29.1 (методы класса _DirectoryIterator_)
`getSize()` - Возвращает **имя каталога** (без имени файла и подкаталога).
 Эта строка дублирует описание `GetPath()`, но мне кажется что здесь должно быть что-то про размер файла.

стр 643 -> таблица 35.2 (_Директивы ограничения ресурсов_)
`max_input_time` - ...и загруженных файлов. Если директива принимает значение -1, по умолчанию принимается значение 60 с.
Вопрос в следующем "если принимает значение -1" - то, что происходит?

стр 695 -> **Условная выборка**
> Оператор "больше" > возвращает TRUE (истину), если левый аргумент больше правого, и FALSE (ложь), если правый аргумент **меньше** или равен левому.

Я думаю ложь он должен возвращать если правый аргумент **больше** левого.

стр 699 -> (первая строка)

> При помощи специальных символов, представленных в табл. 37.8, можно задать.....
Возможно имелась в виду таблица номер 37.10 ? 

Я еще не закончил читать книгу, а ошибки в начале списывал на свое слабое понимание предмета, так что я еще вернусь, большое спасибо за книгу, очень фундаментальный подход.

**Comment by dmitryisaenko** [comment]
Стр.145
В листинге 6.5. есть код по выводу переменной-объекта ($obj), но в примере работы кода его нет. Хотя в дальнейшем пояснении (на след. странице) он упоминается

**Comment by tourniquet** [comment]
Стр. 143, "Проверка существования константы"

> В PHP имеется также функция, которая проверяет, существует ли (была ли определена ранее) константа с указанным именем
> **bool defined(string $name)**

Хотя на странице 141 написанно "а во-вторых, ее имя не предваряется знаком $", поэтому мне кажется не совсем правильно использовать знак $ перед именем константы.

**Comment by 1fran1946** [comment]
Привет из 2019! Добавлю и свои пять копеек
[стр564] возвращается **имя** каталога (надо  **размер**)
[стр913] $**D**ata (регистр)
[стр915] $**D**ata (регистр)
[стр956, 959] d**ea**mon (надо d**ae**mon)

**Comment by TP-Banks** [comment]
Глава 13. Строковые функции (стр. 257)

В конфигурационном файле php.ini изменён синтаксис для строки:

extension=php_mbstring.dll

Теперь:

extension=mbstring

**Comment by qwert130** [comment]
страница 720 

> GIF
> и PNG Moryт содержать одновременно лишь фиксированное кол-во цветов
> (не больше 256)

Дословно не цитирую так как эл. версия книги не позволяет нормально копировать текст.
Вот отрывок из википедии 

 
> PNG имеет следующие основные преимущества перед GIF:
> 
> практически неограниченное[5] количество цветов в изображении (GIF использует в лучшем случае 8-битный цвет);
> 
то есть фото в формате pngможет иметь больше 256 цветов

**Comment by qwert130** [comment]
стр. 730
```
<?php ## Увеличение картинки со сглаживанием.
$tile = imageCreateFromJpeg("sample1.jpg");
$im = imageCreateTrueColor(800, 600);
imageFill($im, 0, 0, imageColorAllocate($im, 0, 255, 0));
imageSetTile($im, $tile);
// Создаем массив точек со случайными координатами.
$p = [];
for ($i = 0; $i < 4; $i++) {
	array_push($p, mt_rand(0, imageSX($im)), mt_rand(0, imageSY($im)));
}
// Рисуем закрашенный многоугольник.
imageFilledPolygon($im, $p, count($p) / 2, IMG_COLOR_TILED);
// Выводим результат.
header("Content-type: image/jpeg");
// Выводим картинку с максимальным качеством (100).
imageJpeg($im, '', 100);
// Можно было сжать с помощью PNG.
#header("Content-type: image/png");
#imagePng($im);
?>

```
У меня результат выглядит как чёрный квадрат с белыми контурами по центру 
Что-то подобное наблюдается, когда стоят пробелы перед откр. тегом php, но тут  в любом случае - проблема
Зато если использовать png, то всё норм
```
 <?php ## Увеличение картинки со сглаживанием.
$tile = imageCreateFromJpeg("sample1.jpg");
$im = imageCreateTrueColor(800, 600);
imageFill($im, 0, 0, imageColorAllocate($im, 0, 255, 0));
imageSetTile($im, $tile);
// Создаем массив точек со случайными координатами.
$p = [];
for ($i = 0; $i < 4; $i++) {
	array_push($p, mt_rand(0, imageSX($im)), mt_rand(0, imageSY($im)));
}
// Рисуем закрашенный многоугольник.
imageFilledPolygon($im, $p, count($p) / 2, IMG_COLOR_TILED);
// Выводим результат.
header("Content-type: image/png");
imagePng($im);
?>

```

**Comment by mar4ehk0** [comment]
Стр 482,
Описание оператора _instanceof_. Примеры кода используют функцию _echoPage_. Но у вас в тексте написано про функцию _moveSize()_.
Оригинальный Текст:
C его использованием фнукцию moveSize()[тут должна быть _echoPage_] можо было бы переписать так, как показано в листнге 23.19.

**Comment by mar4ehk0** [comment]
стр 516
Оригинальный текст: "В листинге 26.6 привиден пример базового синтаксиса конструкции try...catch, применяемой для работы с исключениями. "
Вы неверно указали номер листинга. Номер листинга должен быть 26.7

стр 517
Оригинальный текст: "Именно поэтому результат работы сценария из листинга 25.6 выглядит так:"
Тут также ошибка с номером листинга, должен быть 26.7

**Comment by DaaN88** [comment]
Здравствуйте! Купил третье издание (2020 год выпуска книга). Вчера купил.
Сейчас смотрю опечатки, которые тут еще в 2016 находили и они остались... Как так-то?
Ну и по делу:
В предисловии, 2 абзац (хотя и не выделен как абзац кстати; у абзаца отступ делается), 4 строка:
...менеджерами пактов,....
Наверное так:
менеджерами пакетов?

**Comment by DaaN88** [comment]
Страница 145. Листинг 6.5 Использование var_export().
Приведенный вывод  результат не полный. Нету вывода var_export($obj). Хотя словами, далее по тексту, описывается вывод переменной типа SomeClass.
Полный вывод результата:
### 
       array (
        0 => 1,
        1 => 
        array (
          0 => 'Programs hacking programs. Why?',
          1 => 'д\'Артаньян',
        ),
      )
      SomeClass::__set_state(array(
         'x' => 100,
      ))
###

**Comment by DaaN88** [comment]
А фидбека вообще никакого? Стр. 366: функция strftime - неправильно описаны спецификаторы и применение в Windows не обозначено...

**Comment by Valera8** [comment]
Страница 588. Работа с cookies. "Что такое cookies и как происходит работа с ними, описано в части II". 
На самом деле в части I.

**Comment by DaaN88** [comment]
Страница 398:
в коде (он на странице один)
`$str = preg_replace(`
применены комментарии и перенос на новую строку, а модификаторы всего лишь es. Где модификатор /x? На страницах 396/397 так все про него расписано...

**Comment by DaaN88** [comment]
> Стр 206 в конструкции list() вместо $born, $burn :)

И об этом было указано в 2016-ом году!
А в версии книги 2020 так все и осталось. Наплевать на книгу своим создателям...

**Comment by denis-kadet** [comment]
Добрый день! На стр.1004 рис. 54.9 показана команда для индексации git commit. На странице 1005 написано "Для того чтобы перевести изменения в индексированное состояние, необходимо выполнить команду git add..."

**Comment by gry-dmitrij** [comment]
стр. 647 
"Можно воспользоваться регулярными выражениями:
if (preg_replace..."
Все-таки здесь должно быть preg_match по логике.

**Comment by 1371** [comment]
стр. 28 "Предисловие"

Языки программирования, окончательно оформляются в технологии, окруженные менеджерами _пактов_ ...

Пактов пока вроде не было, а вот **пакеты** встречаются :)

**Comment by igorsimdyanov** [comment]
Всем огромное спасибо за работу. В настоящий момент подготавливается издание "PHP 8". Книга готова на 50%. Исправления, которые затрагивают первую половину книги внесены. Ваша внимательность и труд не пропадут!

**Comment by igorsimdyanov** [comment]
Еще раз всем огромное спасибо за работу! Переписывали, вычитывали несколько раз, а ошибки так и остались неисправленными. Они бы ушли и в новое издание, если бы не ваш труд и внимательность. Все исправления внесены в новое издание (за исключением тех мест, где текст был переписан полностью и из-за этого опечаток не осталось). В настоящий момент издание готово на 100% и идет его корректура.

**Comment by TheoDrag** [comment]
стр. 252
"есть обратная функция ord (), которая по ASCll-коду возвращает символ" 
Наоборот: ord — Convert the first byte of a string to a value between 0 and 255
