### ISSUE TITLE
Отличная книга

### ISSUE THREAD

**Issue by ghost** [igorsimdyanov/php7#6]
Игорь, спасибо Вам и Дмитрию за отличную книгу по PHP 7. 
С нетерпением ждал когда ее доставят и вот сегодня получил! Книга супер, в ней есть все что нужно.
Спасибо Вам за Ваш труд!

P.S. Жду выхода новой редакции книги по MySQL (включающей MySQL 5.7).

**Comment by igorsimdyanov** [comment]
Большое спасибо, за теплый отзыв!

По MySQL 5.7 очень бы хотелось выпустить книгу, но боюсь более оправданно в текущей ситуации было бы ориентироваться на PostgreSQL, который заметно увеличил свою долю и именно за счет MySQL. После того, как MySQL после серии перепродаж оказалась в руках Oracle она довольно медленно развивается, в то время как PostgreSQL, сам по себе являясь уникальной объектно-ориентированной базой здорово развивает в том числе и реляционный функционал (индексы по выражения, оконные функции). К сожалению, MySQL по возможностям отстает от PostgreSQL и такое ощущение, что догонит не скоро (хорошо хоть JSON-поля ввели, но опять как-то не особо до конца, с массивами почти невозможно работать, только с хэшами).

**Comment by ugsite** [comment]
Если Вы не против, буду писать сюда некоторые вопросы по мере прочтения книги.

Стр. 122, абзац 2: "... Иными словами Вы обязаны ставить точку с запятой перед else в конструкции if-else ...". 

Имеется ввиду данный случай?
```php
if (условие)
  выражение;
else
  выражение;
```
В другом случае перед else ставится закрывающая фигурная скобка:
```php
if (условие) {
  выражение;
} else {
  выражение;
}
```

**Comment by ugsite** [comment]
Страница 128, абзац 1: "... Единственное исключение из этого правила - копирование переменной, ссылающейся на объект или массив: в этом случае объект остается в единственном экземпляре, копируется лишь ссылка на него ..."

Согласно [документации](http://php.net/manual/ru/language.operators.assignment.php): "Исключением из обычного для PHP способа присваивания по значению являются объекты (object), которые, начиная с версии PHP 5, присваиваются по ссылке." 

То есть при присвоении переменной массивы копируются по значению.

**Comment by ugsite** [comment]
Страница 164, 3-й абзац снизу: "... директиве **display_errors** в файле php.ini. По умолчанию она **включена в php.ini для рабочего сервера и выключена в php.ini для разработки**."

Согласно комментариям в файле php.ini:
```ini
; display_errors
;   Default Value: On
;   Development Value: On
;   Production Value: Off
```

**Comment by ugsite** [comment]
Страница 218, 1-й абзац: "До версии PHP 7 использование неправильного типа в **строгом режиме** приводил к выдаче ошибки и остановке программы."

Согласно [документации](http://php.net/manual/ru/control-structures.declare.php) строгий режим (strict_types) появился с версии 7.0.0.

**Comment by ugsite** [comment]
Страница 279, последний абзац.

Согласно [документации](http://php.net/manual/ru/function.sort.php) флагов сортировки несколько больше.

**Comment by ugsite** [comment]
Страница 281, 290. Функции пользовательской сортировки по ключам и по значениям.
Описание синтаксиса функций отличается от описания в документации.

Согласно документации к функциям [uksort](http://php.net/manual/ru/function.uksort.php) и [uasort](http://php.net/manual/ru/function.uasort.php):
```php
bool uksort ( array &$array, callable $key_compare_func)
bool uasort ( array &$array, callable $value_compare_func)
```

**Comment by ugsite** [comment]
Глава 15. Математические функции
Согласно [документации](http://php.net/manual/en/function.ceil.php) тип возвращаемого значения функцией ceil - **float**, однако в книге указан **int** (стр. 304).

**Comment by ugsite** [comment]
Глава 16. Работа с файлами и каталогами
Согласно [документации](http://php.net/manual/ru/function.fopen.php) тип возвращаемого значения функцией fopen - resource, однако в книге указан int (стр. 314).

**Comment by ugsite** [comment]
Глава 17. Права доступа и атрибуты файлов

Тип второго аргумента функции chown - mixed, в книге указан string (стр. 348)

Тип возвращаемого значения функции touch - bool, в книге указан int (стр. 352)

**Comment by ugsite** [comment]
Книга правда отличная, очень много полезной информации. 
Если Вы не против по мере дальнейшего прочтения продолжу отмечать некоторые неточности, которые, надеюсь, в следующих редакциях книги будут исправлены.

**Comment by ugsite** [comment]
Глава 21. 
Стр. 414. Функции exit и die в книге описаны как разные функции, но они [эквивалентны](http://php.net/manual/ru/function.die.php).
Стр. 415. Функция [register_shutdown_function](http://php.net/manual/ru/function.register-shutdown-function.php) не возвращает значения после выполнения, в книге указан тип возвращаемого значения int.
Стр. 416. Тип возвращаемого значения функцией [eval](http://php.net/manual/ru/function.eval.php) - mixed, в книге указан тип возвращаемого значения int.

**Comment by ugsite** [comment]
Глава 25. Стр. 494. "Оператор namespace должен располагаться в файле первым, до любых объявлений".

Согласно [документации](http://php.net/manual/ru/language.namespaces.definition.php): "Файл, содержащий пространство имен, должен содержать его объявление в начале перед любым другим кодом, **кроме зарезервированного слова declare**".

**Comment by ugsite** [comment]
Глава 26. Стр. 506. Таблица. "E_ALL" - "Все перечисленные флаги, за исключением E_STRICT".

Согласно [документации](http://php.net/manual/ru/errorfunc.constants.php): "Все поддерживаемые ошибки и предупреждения, за исключением ошибок E_STRICT **до PHP 5.4.0.**"

**Comment by ugsite** [comment]
Глава 26. Стр. 513 "Функция trigger_error() позволяет сгенерировать только ошибки пользовательского уровня, т.е. E_USER_ERROR, E_USER_WARNING и E_USER_NOTICE. Если задан один из этих уровней, функция возвращает FALSE, в противном случае возвращается TRUE".

Согласно [документации](http://php.net/manual/ru/function.trigger-error.php):
1.  "Работает только с семейством констант E_USER", т.е.: E_USER_ERROR, E_USER_WARNING, E_USER_NOTICE **и E_USER_DEPRECATED**.
2. "**Функция возвращает FALSE, если задан неправильный error_type**, и TRUE в остальных случаях."

**Comment by ugsite** [comment]
Глава 26. Стр. 522. "Замечание: К сожалению, в современной версии PHP реализация исключениями интерфейсов (а следовательно, и множественная классификация) не поддерживается. ... попытка перехватить сгенерированное исключение **по имени его интерфейса** (а не по имени класса) не даст результата."

Однако на стр. 523 "Применение интерфейсов дает возможность реализовать множественную классификацию ... Множественная классификация оказывается как нельзя кстати при работе с исключениями". В листинге 26.15 на стр. 525 приводится пример перехвата исключения **по имени интерфейса**.

Ограничения по перехвату исключений по имени интерфейса отсутствуют в  [документации](http://php.net/manual/ru/language.exceptions.php).

**Comment by ugsite** [comment]
Глава 29. Таблица 29.1 "getSize() - Возвращает имя каталога (без имени файла и подкаталога)"

Согласно [документации](http://php.net/manual/ru/directoryiterator.getsize.php): "getSize - Возвращает размер текущего элемента DirectoryIterator"

**Comment by ugsite** [comment]
Глава 30. Стр. 574. Параметр функции: ReflectionParameter "Обратите внимание на то, что у данного отражения нет конструктора".

Согласно [документации](http://php.net/manual/ru/reflectionparameter.construct.php) у данного отражения есть конструктор.

**Comment by ugsite** [comment]
Глава 31. Стр. 585. Тип возвращаемое значение и количество аргументов функции header, указанные в книге, отличаются от [документации](http://php.net/manual/ru/function.header.php)

**Comment by ugsite** [comment]
Глава 31. Стр. 588-589. 
> "Самый распространенный пример использования cookies - имя входа и пароль пользователя, использующего некоторые защищенные ресурсы вашего сайта. Эти данные, конечно же, между открытиями страниц хранятся в cookies, для того, чтобы пользователю не пришлось их каждый раз набирать вручную заново."

В [комментарии](http://php.net/manual/ru/features.cookies.php#36058) к документации по [Cookies](http://php.net/manual/ru/features.cookies.php) сказано:
> "Обычно считается очень плохой практикой хранение имен пользователей и / или паролей в файлах cookie, независимо от того, являются ли они скрытыми."

**Comment by ugsite** [comment]
Глава 31.
Стр. 589. Функция [setcookie](http://php.net/manual/ru/function.setcookie.php). Тип возвращаемого значения bool. В книге указан int.
Стр. 592. Функция [http_build_query](http://php.net/manual/ru/function.http-build-query.php). Тип второго аргумента может быть массивом или объектом, содержащим свойства. В книге указан array.
Стр. 593. Функция [parse_url](http://php.net/manual/ru/function.parse-url.php). Тип возвращаемого значения mixed. В книге указан array. Также отсутствует второй параметр функции.

**Comment by ugsite** [comment]
Глава 32.
Стр. 601. Описание функции **fsockopen** отличается от [документации](http://php.net/manual/ru/function.fsockopen.php). Тип возвращаемого значения resource, в книге int. Второй параметр является не обязательным, в книге - обязательный.

**Comment by ugsite** [comment]
Глава 34. Стр. 627
```php
// Удалить cookie, соответствующую SID
@unset($_COOKIE[session_name()];
```
Данная операция не приведет к удалению cookie. При перезагрузке страницы массив $_COOKIE вернется к прежнему состоянию.

Согласно [документации](http://php.net/manual/ru/function.setcookie.php) чтобы удалить cookie достаточно вызвать функцию setcookie и в качестве срока действия указать какое-либо время в прошлом.
```php
// установка даты истечения срока действия на час назад
setcookie(session_name(), "", time() - 3600);
```

**Comment by igorsimdyanov** [comment]
Огромное спасибо за замечания, мы не можем реагировать на каждое из них. Но поверьте ваша работа не пропадает зря и при выпуске нового издания все они будут учтены.

**Comment by ugsite** [comment]
Глава 37. 

Стр. 686, указано имя столбца id_cat, вместо cat_id, которое определено на стр. 685.

Стр. 693
> Синтаксис оператора **RENAME** аналогичен синтаксису оператора INSERT:

Вместо оператора **REPLACE**, указан оператор ~~RENAME~~.

**Comment by ugsite** [comment]
Глава 37
Стр. 706
Листинг 37.13:
```php
$ver = $pdo->query($query);

// Извлекаем результат
$version = $ver->fetch();
```

> Для выполнения запроса используется объект соединения $pdo и его метод $query, в качестве результата метод возвращает объект класса PDOStatement, который мы сохраняем в переменной **$version**.

Объект класса PDOStatement сохраняется в переменной **$ver**, а не ~~$version~~.
В переменной **$version** сохраняется строка из результирующего набора.

**Comment by ugsite** [comment]
Глава 37.
Стр. 709.
Листинг [37.17](https://github.com/igorsimdyanov/php7/blob/master/mysql/fetch.php)

```php
require_once("connect.php");

$query = "SELECT * FROM catalogs";
$cat = $pdo->query($query);

try {
  while($catalog = $cat->fetch())
    echo $catalog['name']."<br />";
} catch (PDOException $e) {
  echo "Ошибка выполнения запроса: " . $e->getMessage();
}
```
При наличии ошибки в запросе, исключение PDOException не будет поймано, что вызовет ошибку "PHP Fatal error:  Uncaught PDOException".
Для того, чтобы поймать исключение, необходимо разместить вызов метода query в блоке try ... catch.

```php
try {
  $cat = $pdo->query($query);
} catch (PDOException $e) {
  echo "Ошибка выполнения запроса: " . $e->getMessage();
} 
```
В этом случае исключение будет поймано.
В итоге, листинг может выглядеть так:

```php
require_once("connect.php");

$query = "SELECT * FROM catalogs";

try {
  $cat = $pdo->query($query);  
  while($catalog = $cat->fetch())
    echo $catalog['name']."<br />";
} catch (PDOException $e) {
  echo "Ошибка выполнения запроса: " . $e->getMessage();
}
```

**Comment by ugsite** [comment]
Глава 37.
Стр. 712. Заполнение связанных таблиц
В тексте используются имена столбцов **id_news**, **id_content**, в листинге к тексту (37.20) **news_id**, **content_id**.

**Comment by ugsite** [comment]
Глава 38.
Стр. 717. Универсальная функция getimagesize()

1. В книге:
```php
list getimagesize(string $filename)
```

Согласно документации к функции [getimagesize](http://php.net/manual/ru/function.getimagesize.php) у функции может быть второй необязательный параметр **imageinfo**.
```php
array getimagesize ( string $filename [, array &$imageinfo ] )
```

2. В книге указано, что функция возвращает список из элементов:
> ...
Ячейка с индексом 4 содержит число битов ...
Ячейка с индексом 5 содержит количество цветовых каналов ...
...

Согласно [документации](http://php.net/manual/ru/function.getimagesize.php) в возвращаемом массиве могут быть ячейки:
**bits** - глубина цвета, число бит для каждого цвета.
**channels** - принимает значение 3 для RGB картинок и 4 для CMYK.  
Не все типы изображений содержат элементы с каналами (channels) и битрейтом (bits). 

Ячеек с индексами **4, 5** в возвращаемом массиве нет.

**Comment by ugsite** [comment]
Глава 38.
Стр. 719
> В случае Ubuntu, установить расширение можно при помощи команды:
```bash
sudo apt-get install php5-gd
```

Поскольку книга по PHP 7, команда должна быть:
```bash
sudo apt-get install php7.0-gd
```

**Comment by ugsite** [comment]
Глава 38.
Стр. 720. Создание изображения
> Это связано с тем, что JPEG является _**полноцветным**_ (true color) форматом, в то время как GIF и PNG могут единовременно содержать лишь фиксированное (**не больше 256**) количество цветов.

Формат [PNG](https://en.wikipedia.org/wiki/Portable_Network_Graphics) (PNG-24, PNG-32) поддерживает полноцветное изображение с количеством цветов значительно превышающих 256.
Скорее всего в данном обзаце идет речь о формате PNG-8.

**Comment by ugsite** [comment]
Глава 38.
Стр. 722.

В книге:
```php
int imagePng(resource $im [,string $filename] [,int $quality])
int imageJpeg(resource $im [,string $filename] [,int $quality])
int imageGif(resource $im [,string $filename])
```
В документации:
```php
bool imagepng ( resource $image [, mixed $to [, int $quality [, int $filters ]]] )
bool imagejpeg ( resource $image [, mixed $to [, int $quality ]] )
bool imagegif ( resource $image [, mixed $to ] )
```

**Comment by ugsite** [comment]
Глава 42. Стр. 787. Листинг 41.1, 42.2 и абзац между ними.
Указано **PRS-1** вместо **PSR-1**.

**Comment by ghost** [comment]
Глава 42. Стр. 787. Листинг 42.1, 42.2 и абзац между ними.
Указано **PRS-1** вместо PSR-1.

**Comment by ghost** [comment]
Глава 42. Стр. 801
> getProtocolVersion() - возвращает версию HTTP-протокола: либо "1.0", либо "2.0";
> withProtocolVersion() - задает версию HTTP-протокола: либо "1.0", либо "2.0";

Версия [HTTP-протокола](https://ru.wikipedia.org/wiki/HTTP) также может быть "**1.1**"

**Comment by ghost** [comment]
Глава 42. Стр. 802
> Стандарт **PRS**-7 ...

Указано **PRS**-7 вместо PSR-7

**Comment by ghost** [comment]
Глава 43.
В тексте главы указано "**phpDocumentator**" вместо [phpDocumentor](https://www.phpdoc.org/).

**Comment by ghost** [comment]
Глава 44. Листинг 44.4 (и далее в тексте после листинга).
```php
// Удаляем последний символ /, если он имеется
$this->dirname = ltrim($dir_name, "/");
```
Функция [ltrim](https://www.php.net/manual/ru/function.ltrim.php) удаляет пробелы (или другие символы) из **начала** строки.
В данном случае должна быть функция [rtrim](https://www.php.net/manual/ru/function.rtrim.php), она удаляет пробелы (или другие символы) из **конца** строки.

**Comment by igorsimdyanov** [comment]
Огромное спасибо за работу! В настоящий момент подготавливается издание "PHP 8". Книга готова на 50%. Исправления, которые затрагивают первую половину книги внесены. Ваша внимательность и труд не пропадут!

**Comment by igorsimdyanov** [comment]
Еще раз всем огромное спасибо за работу! Переписывали, вычитывали несколько раз, а ошибки так и остались неисправленными. Они бы ушли и в новое издание, если бы не ваш труд и внимательность. Все исправления внесены в новое издание (за исключением тех мест, где текст был переписан полностью и из-за этого опечаток не осталось). В настоящий момент издание готово на 100% и идет его корректура.
