### ISSUE TITLE
Не переписано Предисловие к первому изданию.

### ISSUE THREAD

**Issue by Knayz** [igorsimdyanov/php7#7]
Этот раздел остался из Php 5, где еще остались упоминания php 4. Так же в разделе Благодарности Дмитрия Котерова говорится про издание книги php 5. Конечно, к самому языку это не имеет никакого отношения, всего лишь хотел помочь и сделать книгу лучше. Буду читать книга конечно легендарная, psr, vagrant очень актуально. Спасибо большое за труд.

**Comment by igorsimdyanov** [comment]
Большое спасибо, за замечание, учтем, если будет выпускаться исправленное издание.

**Comment by Knayz** [comment]
Не планируете, обновить книгу php практика создания web-создания, на современном php?

**Comment by igorsimdyanov** [comment]
Мысли есть, но к такой книге нужно тщательно подготовиться. Сейчас язык PHP занимает не 100% и даже не 50% рабочего времени. Это означает, что материал нужно обязательно обкатать на курсах. Подвижки есть, но пока отвлекают другие проекты.
Вообще было бы любопытно, с момента выхода книги, подходы в разработке несколько раз кардинально изменились. Хотелось бы показать современную шаблонизацию, разработку через тестирование, построение нагруженных приложений. Однако, не могу обещать издание в ближайшее время.
