### ISSUE TITLE
Вопросы по изучению

### ISSUE THREAD

**Issue by Gerasimov44** [igorsimdyanov/php7#9]
Здравствуйте, изучаю php с помощью вашей книги. На 144 стр. Константы с динамическим именем. Мне не понятен Листинг и теория.
Теория: "нельзя заранее предугадать ее имя.." , но в листинге имя сразу определяется как $name. А вот значение константы должно по идее менятся, так как используется функция mt_rand. Но определяя константу с димамическим именем как в листинге, она всегда выдает значение 1. Получается константа равна 1? Тогда в чем смысл данного примера? Честно запутался в этой маленькой теме, если разьясните буду благодарен.

**Comment by Gerasimov44** [comment]
И еще, как правильно указывать утилиту curl? Это страница 110. Я ее пробовал прописывать в командной строке, но пишет что curl не является внутренней или внешней командой. 
Причем когда сервер запущен, строка вообще не реагирует на наборы с клавиатуры. После остановки отображается текст curl -I http://lokalhost:4000 и опять же сообщение, что не является внутренней или внешней командой. Как тут быть? Может этой утилитой пользоваться не через командную строку?
Остальное все ясно и понятно. Спасибо.

**Comment by Maunty** [comment]
Какой дистрибутив linux вы используете? если что то семейства debian, тогда выполните sudo apt-get install curl. Я так понимаю терминал перестает реагировать после php -S localhost:400, очевидно, что он ждет окончания выполнения команды - которая как вы понимаете не прекратиться пока вы ее не остановите путем отправки сигнала SIGINT (это ctrl+c), поэтому curl надо давать из другого терминала или запускать встроенный веб-сервер в бэкграунде текущего сеанса терминала, делается это путем добавление символа & в конец команды. Немного сумбурно, но надеюсь вам принесет пользу мой ответ. П.С. - если вы сейчас изучаете php сильно не заостряйте на этом внимание, т.к. то о чем я говорю это базовые знания ОС Linux, об этом читать необходимо в другой литературе.04.04.2017, 19:04, "Gerasimov44" <notifications@github.com>:И еще, как правильно указывать утилиту curl? Это страница 110. Я ее пробовал прописывать в командной строке, но пишет что curl не является внутренней или внешней командой.
Причем когда сервер запущен, строка вообще не реагирует на наборы с клавиатуры. После остановки отображается текст curl -I http://lokalhost:4000 и опять же сообщение, что не является внутренней или внешней командой. Как тут быть? Может этой утилитой пользоваться не через командную строку?
Остальное все ясно и понятно. Спасибо.

**Comment by Maunty** [comment]
name хранит имя константы, но никак не саму константу. А имя константы всегда разное. Сравните echo $name и echo constant($name)04.04.2017, 18:48, "Gerasimov44" <notifications@github.com>:Здравствуйте, изучаю php с помощью вашей книги. На 144 стр. Константы с динамическим именем. Мне не понятен Листинг и теория.
Теория: "нельзя заранее предугадать ее имя.." , но в листинге имя сразу определяется как $name. А вот значение константы должно по идее менятся, так как используется функция mt_rand. Но определяя константу с димамическим именем как в листинге, она всегда выдает значение 1. Получается константа равна 1? Тогда в чем смысл данного примера? Честно запутался в этой маленькой теме, если разьясните буду благодарен.

**Comment by Maunty** [comment]
до меня дошло, что вы работаете в windows, там на сколько мне известно так же есть утилита curl.exe, скачайте ее на просторах интернета и закиньте к себе в папку, например, windows. Тогда ошибка уйдет.04.04.2017, 23:05, "Сергей Ротару" <badwings@yandex.ru>:Какой дистрибутив linux вы используете? если что то семейства debian, тогда выполните sudo apt-get install curl. Я так понимаю терминал перестает реагировать после php -S localhost:400, очевидно, что он ждет окончания выполнения команды - которая как вы понимаете не прекратиться пока вы ее не остановите путем отправки сигнала SIGINT (это ctrl+c), поэтому curl надо давать из другого терминала или запускать встроенный веб-сервер в бэкграунде текущего сеанса терминала, делается это путем добавление символа & в конец команды. Немного сумбурно, но надеюсь вам принесет пользу мой ответ. П.С. - если вы сейчас изучаете php сильно не заостряйте на этом внимание, т.к. то о чем я говорю это базовые знания ОС Linux, об этом читать необходимо в другой литературе.04.04.2017, 19:04, "Gerasimov44" <notifications@github.com>:И еще, как правильно указывать утилиту curl? Это страница 110. Я ее пробовал прописывать в командной строке, но пишет что curl не является внутренней или внешней командой.
Причем когда сервер запущен, строка вообще не реагирует на наборы с клавиатуры. После остановки отображается текст curl -I http://lokalhost:4000 и опять же сообщение, что не является внутренней или внешней командой. Как тут быть? Может этой утилитой пользоваться не через командную строку?
Остальное все ясно и понятно. Спасибо.

**Comment by Gerasimov44** [comment]
Спасибо, за совет. С константой понятно, а вот с curl так и не разобрался. Пока пропущу этот момент,  надеюсь после части X, станет все понятнее.

**Comment by Sikonay** [comment]
Доброго времени суток. У меня есть загвоздка в одном моменте, хотелось бы дальше двигаться но думаю пока не решу не буду читать дальше.
стр 109,  Запуск встроенного сервера.
Не могу запустить index.php
установил 64 битную МС14, скачал и распаковал Non Thread Safe 64 битную в Диск С
указал в path папку c:\php\
учетка является администратором
захожу через командную строку c:\php\www\
там набираю команду php -S localhost:4000 все вроде запускается, только вот при наборе на браузере localhost:4000 пишет не найдет 404 (The requested resource / was not found on this server.)
а в консоле / no such file or directory

**Comment by Sikonay** [comment]
Разобрался почему мне возвращала 404.
файл index.pho в правильной кодировке нужно было создавать
